title: me
author: meow
email: meowoo666@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Try Again
  I have no idea why we need edit so many times
  Just for showing how edurable we are?
  Again and Again.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
