title: Meow's Blog
author: MeoWoo
email: meowoo666@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have nothing to tell.
  But Why?
  I don't understand actually.
  Just because I don't add a comment?
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
